# Generated by Django 3.1.3 on 2020-12-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_main', '0002_testmodelalltypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodelalltypes',
            name='field_null_boolean',
            field=models.BooleanField(null=True),
        ),
    ]
